### ISSUE TITLE
Issue downloading private package from gitlab.com

### ISSUE THREAD

**Issue by mariopulkerkinnovis** [isaaceindhoven/velocita#12]
Hi all.

First at all thank you for this aweseome project.

My setup:
* Proxy is running as docker image
* It is using https
* Secured by basic auth
* I activated the gitlab mirror and added my bearer token

When opening the mirrors.json page the following json is returned:
```json
{
    "mirrors": [
        {
            "url": "//gitlab.com/",
            "path": "/mirror/gitlab/"
        },
        {
            "url": "//codeload.github.com/",
            "path": "/mirror/github-codeload/"
        },
        {
            "url": "//repo.packagist.org/",
            "path": "/mirror/packagist/"
        }
    ]
}
```

For packages downloading from packagist there is no issue
But when trying to download my private package from gitlab it always fails with 404 not found.

When I try to download it manually via postman providing the bearer token, everything works.

Url which I get in composer when doing composer install:
Failed to download package/mypackage from dist: The "https://myproxy.domain.com/mirror/gitlab/api/v4/projects/my-project/mypackage/repository/archive.zip?sha=12342523" ...

And when I try to open the url directly in the browser following json is returned:
```json
{"error":"404 Not Found"}
```

When I try it via postman directly:
https://gitlab.com/api/v4/projects/my-project/mypackage/repository/archive.zip?sha=12342523

So I checked the proxy loggs and found where it tries to download the package:
```
proxy_1  | X.X.X.X - myuser [22/Nov/2023:08:19:12 +0000] "GET /mirror/gitlab/api/v4/projects/my-project/mypackage/repository/archive.zip?sha=12342523 HTTP/1.1" 404 25 "-" "Mozilla/5.0 (X11; Linux x86_64) ..." "X.X.X.X"

proxy_1  | X.X.X.X - myuser [22/Nov/2023:08:19:12 +0000] upstream gitlab.com - [STALE] GET /mirror/gitlab/api/v4/projects/my-project/mypackage/repository/archive.zip?sha=12342523 HTTP/1.1 [-] -ms -b
```
The request to gitlab always ends in the status "STALE".

Please help me!

Thank you in advance!

**Comment by gmta** [comment]
Hi @mariopulkerkinnovis !

GitLab responds with a 404 if authentication failed. Did you use a group token, a personal access token or a deploy token?

Can you please provide the environment variables you have set? Anonymized of course :-)

**Comment by mariopulkerkinnovis** [comment]
Hi @gmta !

Thanks for the fast answer.

I use a personal access token.
With the same token I can download it directly from gitlab.

The https support is managed by traefik.

Here are my env vars:
```
##
# Velocita configuration
##

VELOCITA_URL=https://proxy.domain.com
VELOCITA_HTTP_PORT=8080
VELOCITA_HTTPS_PORT=8443
VELOCITA_TLS_ENABLED=false
#VELOCITA_TLS_CERT_FILE=
#VELOCITA_TLS_KEY_FILE=
VELOCITA_AUTH_TYPE=basic
VELOCITA_CACHE_DIR=/home/user/velocia-proxy/.composer_cache_packages
VELOCITA_HTPASSWD_FILE=/home/user/velocia-proxy/velocita.users

##
# Mirrors configuration
##

# GitHub codeload
MIRROR_GITHUB_CODELOAD_URL=https://codeload.github.com
#MIRROR_GITHUB_CODELOAD_CACHE_SIZE=1g

# Packagist
MIRROR_PACKAGIST_URL=https://repo.packagist.org
MIRROR_PACKAGIST_TYPE=composer
#MIRROR_PACKAGIST_CACHE_EXPIRY=3650d
#MIRROR_PACKAGIST_CACHE_SIZE=1g
#MIRROR_PACKAGIST_ALLOW_REVALIDATE=false
#MIRROR_PACKAGIST_PACKAGES_JSON_EXPIRY=2m
#MIRROR_PACKAGIST_AUTH_TYPE=basic
#MIRROR_PACKAGIST_AUTH_USERNAME=
#MIRROR_PACKAGIST_AUTH_PASSWORD=
#MIRROR_PACKAGIST_USER_AGENT="Velocita Composer Cache"

# GitLab (example)
MIRROR_GITLAB_URL=https://gitlab.com
MIRROR_GITLAB_ALLOW_REVALIDATE=true
MIRROR_GITLAB_TYPE=composer
MIRROR_GITLAB_AUTH_TYPE=bearer
MIRROR_GITLAB_AUTH_PASSWORD="my-access-token"
MIRROR_GITLAB_USER_AGENT="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36"
```

**Comment by gmta** [comment]
Hi @mariopulkerkinnovis ,

Looking at your setup, it seems like you're downloading a repository archive based on a SHA-256 commit hash instead of a Composer package served through a Composer repository. I highly suggest you use a package registry (GitLab offers one, but it is in beta) instead, but you should at least use `MIRROR_GITLAB_TYPE=simple` if you're trying to directly download some ZIP files.

Looking at the GitLab documentation, something seems off with the URL you are using as well:
https://docs.gitlab.com/ee/api/repositories.html#get-file-archive

```
GET /projects/:id/repository/archive[.format]
```

When I try to download the following through my Velocita instance, it works as expected:

```
http://velocita.domain.tld/mirror/gitlab/api/v4/projects/12345678/repository/archive.zip?sha=df0326a4acbc7c401e4152581462286949a56b77
```

Note the project ID instead of name. Where are you getting your URL from exactly?

Finally, it might be helpful if you could share your Traefik logs as well, since you have that running between your client and Velocita.

**Comment by mariopulkerkinnovis** [comment]
Hi @gmta !

Ahhh I used not the project ID, instead I used the project path :exploding_head: !
That solved my issue.
Thank you so much!
Maybe you can add this information to the .env.dist or readme so the next one does not run into the same issue :rofl: .

**Comment by mariopulkerkinnovis** [comment]
Ok I found the issue in my docker-compose.json side :face_with_spiral_eyes: .
I defined my private package originally as vcs and not as composer. Thats why it did not use the project ID.
I'm sorry for wasting your time @gmta :smiling_face_with_tear: !

**Comment by gmta** [comment]
No problem, glad you got it resolved! :^)

> I defined my private package originally as vcs and not as composer.

Just to be sure: did you still use the exact same URL in Postman as through Velocita?

**Comment by mariopulkerkinnovis** [comment]
I updated my composer.json according to the composer webpage and that solved it.
https://docs.gitlab.com/ee/user/packages/composer_repository/
After I updated the composer.lock and the the url contains now the project id and this works fine. 
Also in postman the url with project ID works.
